name: Development

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'

  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  developement:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'
          check-latest: true
          cache: true
          cache-dependency-path: ./deadlines/go.sum
      - run: |
          cd ./deadlines/cmd && go test && go build .
